### ISSUE TITLE
Error loading mod on startup with registries

### ISSUE THREAD

**Issue by dreckz** [eideehi/Perks#1]
Mod does not load up due to provider modjar not being installed
![image](https://user-images.githubusercontent.com/59788491/74595105-5d614080-5003-11ea-8624-ce8b24922469.png)

**Comment by eideehi** [comment]
I have experienced this error during development. In my case, it happened only once, but it doesn't happen from next time. Does it happen every time?

**Comment by MLMII** [comment]
It happens with me every time, here is the "latest.log".



[latest.log](https://github.com/eideehi/Perks/files/4237876/latest.log)

**Comment by eideehi** [comment]
Thank you for the information. In version 1.15.2-4, I made a few changes. If the crash still occurs, please provide the error log again.

**Comment by Bobbypins42** [comment]
there is still a problem
it says

"Perks ( perks ) encountered an error during the load_registries event phase 
Register < Perk > is empty

here is my latest log

[latest.log](https://github.com/eideehi/Perks/files/4240031/latest.log)

**Comment by eideehi** [comment]
Thank you for the report. Further fixes have been made in version 1.15.2-5, but may still crash. In that case, please submit the error log again.

**Comment by eideehi** [comment]
This issue is fixed in version 1.1.5.2-6.
