### ISSUE TITLE
Singleplayer crash on loading world

### ISSUE THREAD

**Issue by dreckz** [eideehi/Perks#2]
MC:1.15.2
Perks: 2-7

When a world is created and I attempt to load back into the world, it ends up crashing.  This is not a 100% occurance, but happens often enough.  It ended up making the crash report below:

[crash-2020-02-29_02.31.00-server.txt](https://github.com/eideehi/Perks/files/4270084/crash-2020-02-29_02.31.00-server.txt)

**Comment by eideehi** [comment]
Thanks for the report, it should have been fixed in version 1.15.2-8.

**Comment by dreckz** [comment]
Thanks!
